"""campaign asset referential integrity

Revision ID: e31efbe1cd6c
Revises: 40284045f31e
"""
from alembic import op
import sqlalchemy as sa

revision = 'e31efbe1cd6c'
down_revision = '40284045f31e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_assets',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'asset_id')
    )
    op.create_index(op.f('ix_campaign_assets_asset_id'), 'campaign_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_campaign_assets_campaign_id'), 'campaign_assets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_assets_org_id'), 'campaign_assets', ['org_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_assets_org_id'), table_name='campaign_assets')
    op.drop_index(op.f('ix_campaign_assets_campaign_id'), table_name='campaign_assets')
    op.drop_index(op.f('ix_campaign_assets_asset_id'), table_name='campaign_assets')
    op.drop_table('campaign_assets')
    # ### end Alembic commands ###
